2017-11-19 14:17:04.472 [error] <0.157.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.157.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:17:04.472 [error] <0.148.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:17:04.473 [error] <0.146.0> CRASH REPORT Process <0.146.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:37:06.650 [error] <0.164.0> ** Connection attempt from disallowed node c286@localhost ** 
2017-11-19 14:37:49.725 [error] <0.166.0> ** Connection attempt from disallowed node c329@localhost ** 
2017-11-19 14:38:57.856 [error] <0.165.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:38:57.858 [error] <0.156.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:38:57.859 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:54:43.445 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:54:43.447 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:54:43.447 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:55:58.459 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:55:58.461 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:55:58.461 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 15:58:05.945 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 15:58:05.946 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 15:58:05.947 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 16:09:35.717 [error] <0.169.0>@logic_server:loop CRASH REPORT Process <0.169.0> with 0 neighbours crashed with reason: call to undefined function logic_server:loop(#Port<0.3494>)
2017-11-19 18:38:26.611 [error] <0.170.0>@logic_server:loop CRASH REPORT Process <0.170.0> with 0 neighbours crashed with reason: call to undefined function logic_server:loop(#Port<0.3559>)
2017-11-22 22:21:59.461 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("debug logic_server get client ip error~n", [#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,...]) line 170 in lists:map/2 line 1239
2017-11-22 22:21:59.462 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}}
2017-11-22 22:21:59.488 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-22 22:21:59.488 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}} in context child_terminated
2017-11-24 01:50:04.685 [error] <0.161.0>@persistence:get_device_id_mapping CRASH REPORT Process <0.161.0> with 0 neighbours crashed with reason: call to undefined function persistence:get_device_id_mapping()
2017-11-24 01:50:04.685 [error] <0.153.0>@persistence:get_device_id_mapping Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason call to undefined function persistence:get_device_id_mapping() in context start_error
2017-11-24 01:50:04.685 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_device_id_mapping,[],[]},{memcache,init_deviceid_index,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 02:11:32.746 [error] <0.161.0>@persistence:dets_foldl:74 CRASH REPORT Process <0.161.0> with 0 neighbours crashed with reason: bad argument in call to dets:first(user_dets) line 1266 in persistence:dets_foldl/3 line 74
2017-11-24 02:11:32.746 [error] <0.153.0>@persistence:dets_foldl:74 Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason bad argument in call to dets:first(user_dets) line 1266 in persistence:dets_foldl/3 line 74 in context start_error
2017-11-24 02:11:32.746 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{badarg,[{dets,first,[user_dets],[{file,"dets.erl"},{line,1266}]},{persistence,dets_foldl,3,[{file,"persistence.erl"},{line,74}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,...}} in application_master:init/4 line 134
2017-11-24 02:13:46.186 [error] <0.160.0>@persistence:init CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: call to undefined function persistence:init()
2017-11-24 02:13:46.186 [error] <0.153.0>@persistence:init Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason call to undefined function persistence:init() in context start_error
2017-11-24 02:13:46.187 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{undef,[{persistence,init,[],[]},{init_base,init,1,[{file,"init_base.erl"},{line,24}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 02:16:49.251 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("persistence:init_dets ~w success ~p", [user_dets]) line 170 in lists:map/2 line 1239
2017-11-24 02:16:49.251 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}}
2017-11-24 02:16:49.260 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-24 02:16:49.260 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}} in context child_terminated
2017-11-24 02:16:49.262 [error] <0.160.0>@user_db:init:23 CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23
2017-11-24 02:16:49.262 [error] <0.153.0>@user_db:init:23 Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23 in context start_error
2017-11-24 02:16:49.262 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}} in application_master:init/4 line 134
2017-11-24 14:24:33.383 [error] <0.160.0>@user_db:init:23 CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23
2017-11-24 14:24:33.383 [error] <0.153.0>@user_db:init:23 Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23 in context start_error
2017-11-24 14:24:33.384 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}} in application_master:init/4 line 134
2017-11-24 14:26:45.354 [error] <0.165.0>@persistence:get_max_uid CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: call to undefined function persistence:get_max_uid()
2017-11-24 14:26:45.354 [error] <0.153.0>@persistence:get_max_uid Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason call to undefined function persistence:get_max_uid() in context start_error
2017-11-24 14:26:45.355 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_max_uid,[],[]},{memcache,init,1,[{file,"memcache.erl"},{line,87}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 14:53:28.497 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("logic_server:process_msg failed ~w ~p~n", [error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,...>>},...]) line 170 in lists:map/2 line 1239
2017-11-24 14:53:28.498 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}}
2017-11-24 14:53:28.546 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-24 14:53:28.546 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}} in context child_terminated
2017-11-24 15:03:29.983 [error] <0.166.0>@logic_servre:init CRASH REPORT Process <0.166.0> with 0 neighbours crashed with reason: call to undefined function logic_servre:init()
2017-11-24 15:03:29.983 [error] <0.153.0>@logic_servre:init Supervisor egame_sup had child init_sup started with init_sup:start_link() at undefined exit with reason call to undefined function logic_servre:init() in context start_error
2017-11-24 15:03:29.984 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_sup,{undef,[{logic_servre,init,[],[]},{init_sup,init,1,[{file,"init_sup.erl"},{line,29}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-29 17:14:07.342 [error] <0.165.0>@persistence:-get_device_id_dict/0-fun-0-:53 CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: no match of right hand value [{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}] in persistence:'-get_device_id_dict/0-fun-0-'/3 line 53
2017-11-29 17:14:07.342 [error] <0.153.0>@persistence:-get_device_id_dict/0-fun-0-:53 Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason no match of right hand value [{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}] in persistence:'-get_device_id_dict/0-fun-0-'/3 line 53 in context start_error
2017-11-29 17:14:07.342 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{{badmatch,[{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}]},[{persistence,'-get_device_id_dict/0-fun-0-',3,[{file,"persistence.erl"},{line,53}]},{persistence,dets_foldl_0,4,[{file,"persistence.erl"},{line,78}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,140}]},{memcache,...},...]}}},...} in application_master:init/4 line 134
2017-11-29 17:36:35.105 [error] <0.38.0> Loading of /home/lifan/egame/server/ebin/tcp_server.beam failed: not_purged
2017-11-29 18:51:50.621 [error] <0.169.0>@net_server_sup:get_base_params:66 CRASH REPORT Process <0.169.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 66
2017-11-29 18:51:50.621 [error] <0.153.0>@net_server_sup:get_base_params:66 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 66 in context start_error
2017-11-29 18:51:50.627 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"net_server/net_server_sup.erl"},{line,66}]},{net_server_sup,map_fun,1,[{file,"net_server/net_server_sup.erl"},{line,50}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,init,1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{supervisor,...},...]}}},...} in application_master:init/4 line 134
2017-11-30 20:57:15.447 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("down msg is ~p~n", {down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}) line 170 in lists:map/2 line 1239
2017-11-30 20:57:15.447 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}}
2017-11-30 20:57:15.506 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-30 20:57:15.507 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in context child_terminated
2017-11-30 21:00:03.927 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("down msg is ~p~n", {down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}) line 170 in lists:map/2 line 1239
2017-11-30 21:00:03.928 [error] <0.11754.0> gen_server <0.11754.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}}
2017-11-30 21:00:03.928 [error] <0.11754.0> CRASH REPORT Process <0.11754.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-30 21:00:03.928 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.11754.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in context child_terminated
